### PR TITLE
update wgpu to 0.17

### PR DESCRIPTION
**Pull request by barzamin**
the required changes are trivial. `wgpu::util::initialize_adapter_from_env`'s signature changed; the backend_bits parameter was removed. allowed backends are now fully constrained by the instance's enabled set (see [the changelog](https://github.com/gfx-rs/wgpu/blob/trunk/CHANGELOG.md#initialize_adapter_from_env-argument-changes)).

### CODE REVIEW

**Comment by parasyte** [comment]
The new version of `egui` is requiring Rust 1.70. We can increment the MSRV for this. The last time this happened was in #320.

It's a bit challenging because the MSRV in the policy will need to be 1.70, but the crate itself can technically be on an older version (perhaps [remaining on 1.64](https://github.com/parasyte/pixels/blob/705f22b60d6bf720b4bd696f43e69f1ffa057921/Cargo.toml#L7)?) so that it can be used with older compilers when `egui` is not used.

**Comment by barzamin** [comment]
I can bump `MSRV.md` and the CI config if you want, unless you'd prefer to touch the policy stuff yourself (I think the PR is editable by maintainers).

**Comment by parasyte** [comment]
You are welcome to give it a shot if you'd like to see this land sooner than I could get around to it! I have some free time on Sunday which might be the soonest I could manage.

**Review by parasyte — APPROVED** [review]
Perfect! Thank you.

**Pull request merged**
