### PR TITLE
Implement resize functionality for minimal-web example

### PR DESCRIPTION
**Pull request by MarkAnthonyM**
Took a little longer than I expected. I realized I accidently broke the native compilation option.

I saw the discussion about moving the boilerplate stuff into a different crate as a feature or something. Would that be difficult to do? I'd love to take a stab at automizing the wasm stuff, but don't have a lot of confidence in my coding skill. Might need some lite mentorship, but I'd love to tackle it as a learning exercise.

### CODE REVIEW

**Comment by parasyte** [comment]
There are a few nitpick things to fix, like running `cargo fmt` on it. I have a little refactor that I'll apply to #218 after CI is passing here.

**Comment by MarkAnthonyM** [comment]
Hmm, that's weird. I remember running cargo fmt, not sure why the CI failed there. I didn't run it with the same flags the CI test is using, that's probably why

**Comment by parasyte** [comment]
It needs the `--workspace` arg to format all crates. By default it will only format the main library crate.

**Comment by parasyte** [comment]
> I saw the discussion about moving the boilerplate stuff into a different crate as a feature or something. Would that be difficult to do?

I'm personally not entirely sure how this should be done. I first thought about an extension trait for `winit::Window` for providing resize capability ... And it works!

```rust

#[cfg(target_arch = "wasm32")]
trait WinitWeb {
    /// Add a canvas element to the HTML body and enable resize support.
    fn init_web(self: &Rc<Self>);

    /// Get the size of the browser client area.
    fn get_client_size() -> LogicalSize<f64>;
}

#[cfg(target_arch = "wasm32")]
impl WinitWeb for winit::window::Window {
    fn init_web(self: &Rc<Self>) {
        use wasm_bindgen::JsCast;
        use winit::platform::web::WindowExtWebSys;

        // Attach winit canvas to body element
        web_sys::window()
            .and_then(|win| win.document())
            .and_then(|doc| doc.body())
            .and_then(|body| {
                body.append_child(&web_sys::Element::from(self.canvas()))
                    .ok()
            })
            .expect("couldn't append canvas to document body");

        // Initialize winit window with current dimensions of browser client
        self.set_inner_size(Self::get_client_size());

        let winit_window = Rc::clone(&self);
        let closure = wasm_bindgen::closure::Closure::wrap(Box::new(move |_e: web_sys::Event| {
            winit_window.set_inner_size(Self::get_client_size());
        }) as Box<dyn FnMut(_)>);

        // Listen for resize event on browser client. Adjust winit window dimensions on event trigger
        let client_window = web_sys::window().unwrap();
        client_window
            .add_event_listener_with_callback("resize", closure.as_ref().unchecked_ref())
            .unwrap();

        closure.forget();
    }

    fn get_client_size() -> LogicalSize<f64> {
        let client_window = web_sys::window().unwrap();
        LogicalSize::new(
            client_window.inner_width().unwrap().as_f64().unwrap(),
            client_window.inner_height().unwrap().as_f64().unwrap(),
        )
    }
}
```

With this extension trait, the WASM-specific part of `run` becomes just a call to `window.init_web()`. I would really like to encapsulate the bifurcated `main`, though.

For general purpose, the `init_web` method should panic if a canvas was already added to the body. Prevent calling it twice and doubling the canvas element and resize listener.

I'm open to bikeshedding the method names and the design. Any ideas for improving `main`?

**Comment by parasyte** [comment]
Thanks! Let's continue discussion in #218

**Pull request merged**
