### PR TITLE
[Optimization] Improve readability

### PR DESCRIPTION
**Pull request by imizao**
Hello, sorry to bother you!

I know that your code is perfect. I would like to submit two small changes to improve readability. The changes are [`count_neibs`](https://github.com/imizao/pixels/blob/future-001/examples/conway/src/main.rs#L253-L286) and [`grid_idx`.](https://github.com/imizao/pixels/blob/future-001/examples/conway/src/main.rs#L338-L343)

If there are any deficiencies, I can change them at any time!

Thanks for the merge!

### CODE REVIEW

**Comment by parasyte** [comment]
Hello!

I have a bit of contextual historical information, here. I didn't write the conway example, but I remember it had some performance issues prior to the original merge. These two commits fixed it:

- 94e87c195a30898fc6784ff3bc7de3e819fa9ec9
- 8c7db9322acafe4fdfb8a83c9d33e3bb282b9e5a

Because this PR changes the same function, I have to ask. Have you done any profiling while doing this work? I would be interested in the results. If performance improves or is relatively the same, then I'll gladly accept this PR. I don't think it would be good if this regresses, though.

----

A totally non-scientific benchmark shows a potential performance regression; Running the example with debug build runs much slower for me. The release build shows no real difference.

`count_neibs()` is called for every pixel in the buffer, so the addition of a Vec allocation in this hot loop is going to be very problematic. The iterator might also prevent all kinds of autovectorization transformations. But these are just guesses.

**Comment by imizao** [comment]
> Hello!
> 
> I have a bit of contextual historical information, here. I didn't write the conway example, but I remember it had some performance issues prior to the original merge. These two commits fixed it:
> 
> * [94e87c1](https://github.com/parasyte/pixels/commit/94e87c195a30898fc6784ff3bc7de3e819fa9ec9)
> * [8c7db93](https://github.com/parasyte/pixels/commit/8c7db9322acafe4fdfb8a83c9d33e3bb282b9e5a)
> 
> Because this PR changes the same function, I have to ask. Have you done any profiling while doing this work? I would be interested in the results. If performance improves or is relatively the same, then I'll gladly accept this PR. I don't think it would be good if this regresses, though.
> 
> A totally non-scientific benchmark shows a potential performance regression; Running the example with debug build runs much slower for me. The release build shows no real difference.
> 
> `count_neibs()` is called for every pixel in the buffer, so the addition of a Vec allocation in this hot loop is going to be very problematic. The iterator might also prevent all kinds of autovectorization transformations. But these are just guesses.

Yes, I overlooked the performance considerations!

Your advice matters!

I'll try to do some performance comparisons above!

**Comment by imizao** [comment]
|                                                                   | All Samples                              | ConwayGrid   Samples                                                                                           | Proportion |
| --------------------------------------------------------------------------- | ---------------------------------------- | --------------------------------------------------------------------------------- | ------------------------ | 
| [**no vec![]**](https://github.com/imizao/pixels/blob/test-01/examples/conway/flamegraph.svg) | 7340           | 2863       | 39.01% |
| [**vec![]**](https://github.com/imizao/pixels/blob/test-02/examples/conway/flamegraph.svg)      | 34830 | 25499 | 73.21% |

Before change -- no vec![]

image

After change -- vec![]

image


# Conclusion: merging is not recommended!

After many tests, `no vec![]` is mostly at 30% ~70%, and `vec![]` is mostly at 60% ~70%

Maybe my analysis is not very accurate!

**Comment by imizao** [comment]
> @imizao Nice analysis! It looks like this confirms my suspicion and what I was seeing with the baseline debug builds.
> 
> However, I would like to include the readability patch for the `grid_idx` method. That part of the PR looks promising. If you would like to either revert the change to the `count_neibs` method, I will get that merged ASAP!

Yes, I revert the changes to the `count_neibs` method！

Thank you very much for your correction, very pleasant cooperation ; )

### Supplementary Note

Regarding the test, I would like to add:
It is the node that has been statically ended every time!
As the picture shows:

image

**Comment by imizao** [comment]
@parasyte  Hi! I saw that I added three commits with one change, should I close the pull request first?

**Comment by parasyte** [comment]
> @parasyte Hi! I saw that I added three commits for one change. If I want to make one commit, should I close the pull request first?

No, it's ok like this. I will squash all commits into one for the merge. Thank you! It looks great.

> Regarding the test, I would like to add:
> Every time it ends with a static node!

You can draw new nodes by dragging with the mouse cursor in the window. :)

**Pull request merged**
